version: '3'
services:
  synapse:
    image: docker.io/matrixdotorg/synapse:latest
    restart: unless-stopped
    environment:
      - SYNAPSE_CONFIG_PATH=/cfg/homeserver.yaml
    volumes:
      - ./test_server/data/synapse:/data
      - ./test_server/synapse:/cfg
    depends_on:
      - db
    ports:
      - 8008:8008/tcp
  proxy:
    image: docker.io/nginx:latest
    environment:
      - NGINX_ENTRYPOINT_QUIET_LOGS=1
    ports: 
      - 8000:80/tcp
    volumes:
      - ./test_server/nginx:/etc/nginx/conf.d
  db:
    image: docker.io/postgres:12-alpine
    environment:
      - POSTGRES_USER=synapse
      - POSTGRES_PASSWORD=beepboop
      - POSTGRES_INITDB_ARGS=--encoding=UTF-8 --lc-collate=C --lc-ctype=C
    volumes:
      - ./test_server/data/db:/var/lib/postgresql/data
