version: '3'
services:
  dendrite:
    image: docker.io/matrixdotorg/dendrite-monolith:latest
    restart: unless-stopped
    volumes:
      - ./test_server/data/dendrite:/data
      - ./test_server/dendrite:/etc/dendrite
    depends_on:
      - db
    ports:
      - 8008:8008/tcp
  db:
    image: docker.io/postgres:12-alpine
    environment:
      - POSTGRES_USER=dendrite
      - POSTGRES_PASSWORD=beepboop
      - POSTGRES_DATABASE=dendrite
      - POSTGRES_INITDB_ARGS=--encoding=UTF-8 --lc-collate=C --lc-ctype=C
    volumes:
      - ./test_server/data/db:/var/lib/postgresql/data
    ports:
      - 5432:5432/tcp
