listen: 127.0.0.1:4000
synapse:
  host: http://127.0.0.1:8008
  db:
    user: synapse
    password: beepboop
    host: localhost
    database: synapse
bot:
  user: '@relay:test.local'
  homeserver_url: http://127.0.0.1:8008
  state_store: ./test_server/data/state_store
  db:
    user: synapse
    password: beepboop
    host: localhost
    database: proxy
